import React, { useEffect, useLayoutEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Award, BrainCircuit, Check, Code2, ExternalLink, Globe2, Layers3, Mail, MapPin, Menu, Send, Sparkles, Workflow, X } from 'lucide-react';




const projects = [
 {id:'nexora',n:'01',name:'Nexora',type:'Web',category:'Business analytics dashboard',desc:'Designed and developed a responsive dashboard to make everyday business data easier to explore.',tech:['React','JavaScript','REST APIs'],art:'chart',overview:'A full-stack learning project exploring clear data presentation and useful dashboard interactions.',problem:'Business information can be hard to scan when it is spread across dense tables and disconnected views.',approach:'Built a simple dashboard layout with summary cards, reusable charts and responsive navigation, then connected sample data through a REST API.',features:['Responsive overview and chart panels','Reusable data visualisation components','API driven sample activity feed'],learned:'Improved my understanding of data presentation, component structure and REST API integration.',outcome:'A complete responsive dashboard prototype that works across desktop and mobile.'},
 {id:'velora',n:'02',name:'Velora',type:'E-commerce',category:'E-commerce website',desc:'Designed and built a friendly online storefront concept for a modern lifestyle brand.',tech:['React','CSS','Node.js'],art:'shop',overview:'A product discovery and shopping experience built as a responsive full-stack project.',problem:'The concept needed to make browsing a small curated collection feel straightforward on every screen.',approach:'Created a clear catalogue, product detail layout and lightweight cart flow, with a calm visual system and mobile-first styling.',features:['Product listing and detail views','Responsive cart interaction','Clear category navigation'],learned:'Practised designing a consistent storefront and connecting user interface state to backend routes.',outcome:'A polished e-commerce prototype with a complete browse-to-cart journey.'},
 {id:'medilytics',n:'03',name:'Medilytics',type:'AI / ML',category:'Healthcare dashboard prototype',desc:'Built a healthcare dashboard prototype for exploring operational data and simple trends.',tech:['React','Python','FastAPI'],art:'health',overview:'A dashboard prototype for presenting sample clinic operations data in a readable way.',problem:'Operational figures are easier to discuss when they can be reviewed together rather than as isolated numbers.',approach:'Grouped key indicators and simple trend views into a clean interface, with a small Python API serving demo data.',features:['Operational overview cards','Simple trend visualisations','Responsive dashboard layout'],learned:'Learned to shape API data for a user interface and communicate prototype limitations clearly.',outcome:'A working prototype suitable for exploring how a small team could review shared operational signals.'},
 {id:'flowpilot',n:'04',name:'Flowpilot',type:'Automation',category:'Task automation tool',desc:'Created a small workflow tool concept to connect common steps in a repeatable task.',tech:['React','Node.js','REST APIs'],art:'flow',overview:'A practical automation prototype focused on representing a task as a set of clear steps.',problem:'Repeated admin tasks are easy to forget and difficult to track when the steps live in different places.',approach:'Designed a lightweight workflow canvas and connected a few demo actions through API endpoints.',features:['Simple workflow step editor','Status indicators for each action','API integration examples'],learned:'Built confidence working with asynchronous API calls, loading states and clear feedback.',outcome:'An end-to-end automation concept that demonstrates how connected tools could reduce repetitive work.'},
 {id:'urbanpulse',n:'05',name:'Urbanpulse',type:'AI / ML',category:'Traffic monitoring prototype',desc:'Explored how a simple computer vision prototype could represent traffic observations.',tech:['Python','OpenCV','React'],art:'map',overview:'A learning prototype combining sample traffic observations with a simple visual monitoring view.',problem:'Raw counts are not especially useful unless they are presented in a way that is easy to compare.',approach:'Used a small OpenCV experiment to explore object detection concepts and displayed prepared results in a web dashboard.',features:['Sample monitoring overview','Location based result cards','Computer vision experiment'],learned:'Explored basic computer vision workflows and the importance of explaining the limits of prototype data.',outcome:'A demonstration of connecting a small AI/ML experiment to a readable web interface.'},
 {id:'finora',n:'06',name:'Finora',type:'Web',category:'Personal finance dashboard',desc:'Designed and developed a personal finance dashboard for reviewing everyday spending.',tech:['React','JavaScript','Charts'],art:'finance',overview:'A frontend dashboard concept for reviewing income, spending and personal budgeting categories.',problem:'A long list of transactions can make it difficult to see simple spending patterns at a glance.',approach:'Created a compact overview with category summaries, a monthly chart and a responsive transaction list.',features:['Monthly income and expense summary','Category breakdown cards','Responsive transaction list'],learned:'Practised data visualisation, interface hierarchy and accessible responsive layouts.',outcome:'A clear finance dashboard prototype for helping users review their habits.'}
];
const skillGroups=[
 ['Frontend','Comfortable with',['React','JavaScript','HTML','CSS','Tailwind CSS']],
 ['Backend','Working knowledge',['Node.js','Express','Python','REST APIs']],
 ['AI / ML','Working knowledge',['Python','Scikit-learn','OpenCV','TensorFlow']],
 ['Tools','Comfortable with',['Git','GitHub','VS Code','Firebase','Vercel']]
];
const services=[
 ['01','Web Development','Responsive websites and web applications built with clear structure and practical features.',Code2],
 ['02','AI & Machine Learning','Small AI/ML prototypes that explore a real use case and make the result easy to understand.',BrainCircuit],
 ['03','UI Implementation','Careful, responsive frontend implementation from a design direction or product brief.',Layers3],
 ['04','Automation & APIs','Useful integrations that connect services and simplify repeatable tasks.',Workflow]
];
const certificates=[
 ['AWS Cloud Foundations','Cloud Foundations Academy','2025'],
 ['React Web Development','Frontend Learning Studio','2025'],
 ['Python for Data Science','Data Skills Institute','2024'],
 ['Introduction to Machine Learning','Applied AI Academy','2024'],
 ['Git & GitHub Essentials','CodePath Learning','2024']
];
const testimonials=[
 ['Arjun was very patient with our requirements and delivered a clean website that worked well on mobile.','Rohan','Small Business Owner'],
 ['He understood the design quickly and turned our idea into a working website.','Meera','Startup Founder'],
 ['Arjun was thoughtful about feedback and made the project easy to follow from start to finish.','Kabir','Community Project Lead']
];
const nav=[['About','about'],['Skills','skills'],['Projects','projects'],['Experience','experience'],['Certificates','certificates'],['Contact','contact']];

function Art({type}) { return <div className={'r-art r-art-'+type} aria-label={type+' project interface preview'}>
 <div className="r-window"><div className="r-window-top"><span/><span/><span/><b>{type==='shop'?'VELORA / SHOP':type.toUpperCase()+' / OVERVIEW'}</b><i>•••</i></div>
 {type==='chart'&&<><div className="r-mini-title">Monthly activity <strong>+12.8%</strong></div><div className="r-bars">{[35,52,43,70,54,84,66,93,73,88,62,100].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div><div className="r-card-row"><span>OVERVIEW<b>8,420</b></span><span>ACTIVE USERS<b>1,284</b></span><span>GROWTH<b>12.8%</b></span></div></>}
 {type==='shop'&&<div className="r-shop"><div className="r-shop-nav">VELORA <span>HOME &nbsp; OBJECTS &nbsp; ABOUT</span></div><div className="r-shop-body"><div className="r-vase"/><div><small>THE EVERYDAY EDIT</small><h4>Made for<br/>your moments.</h4><span>Explore the collection →</span></div></div></div>}
 {type==='health'&&<><div className="r-health-title">Clinic snapshot <b>THIS MONTH</b></div><div className="r-health-cards"><span>Appointments<strong>248</strong><i/></span><span>Follow-ups<strong>86%</strong><i/></span><span>Avg. wait<strong>14 min</strong><i/></span></div><div className="r-health-chart">{[35,45,60,42,78,64,85,58,72,95,66,82].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div></>}
 {type==='flow'&&<div className="r-flow"><span>New request <small>TRIGGER</small></span><i/><span>Review details <small>STEP 01</small></span><i/><span>Send update <small>STEP 02</small></span></div>}
 {type==='map'&&<><div className="r-map"><i/><i/><i/><i/><i/><i/><b>●</b><b>●</b><b>●</b></div><div className="r-map-footer">TRAFFIC SAMPLE <strong>Monitoring view</strong></div></>}
 {type==='finance'&&<><div className="r-fin-title">Monthly overview <strong>₹ 42,850</strong><small>AVAILABLE BALANCE</small></div><div className="r-fin-wave"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="r-fin-bottom"><span>INCOME <b>₹ 58,400</b></span><span>SPENDING <b>₹ 15,550</b></span></div></>}
 </div></div>}
function Footer(){return <footer className="r-footer"><a className="r-brand" href="#home"><span className="r-mark">AM</span><span><b>ARJUN MALHOTRA</b><small>JUNIOR FULL-STACK DEVELOPER</small></span></a><p>Designed and built with care.</p><div><a href="#about">About</a><a href="#projects">Projects</a><a href="#contact">Contact</a></div><small>© 2026 Arjun Malhotra · Fictional portfolio concept</small></footer>}
function App(){
 const [menu,setMenu]=useState(false),[filter,setFilter]=useState('All'),[modal,setModal]=useState(null),[caseId,setCaseId]=useState(null),[testimonial,setTestimonial]=useState(0),[form,setForm]=useState({name:'',email:'',type:'',message:''}),[sent,setSent]=useState(false),[scrolled,setScrolled]=useState(false);
 const scrollToSection=(id,behavior='smooth',updateHash=true)=>{const target=document.getElementById(id);if(!target)return;const anchor=id==='home'?target:(target.querySelector('.r-section-label')||target);if(id!=='home')setScrolled(true);else setScrolled(false);if(updateHash&&location.hash!=='#'+id)history.pushState(null,'','#'+id);const styles=getComputedStyle(document.documentElement);const compact=parseFloat(styles.getPropertyValue('--r-nav-compact-height'))||72;const gap=parseFloat(styles.getPropertyValue('--r-scroll-gap'))||14;const top=Math.max(0,window.scrollY+anchor.getBoundingClientRect().top-(id==='home'?0:compact+gap));if(behavior==='auto'){const prior=document.documentElement.style.scrollBehavior;document.documentElement.style.scrollBehavior='auto';window.scrollTo({top,behavior:'auto'});document.documentElement.style.scrollBehavior=prior}else window.scrollTo({top,behavior});};
 useLayoutEffect(()=>{const update=()=>{setScrolled(window.scrollY>20);const match=location.hash.match(/^#\/projects\/([a-z-]+)/);setCaseId(match?.[1]||null)};update();addEventListener('scroll',update,{passive:true});addEventListener('hashchange',update);return()=>{removeEventListener('scroll',update);removeEventListener('hashchange',update)}},[]);
 useLayoutEffect(()=>{const id=decodeURIComponent(location.hash.slice(1));if(id&&!id.startsWith('/')&&document.getElementById(id))scrollToSection(id,'auto',false)},[]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape')setMenu(false)};addEventListener('keydown',close);return()=>removeEventListener('keydown',close)},[]);
 useLayoutEffect(()=>{const items=document.querySelectorAll('.r-section,.r-case-head,.r-case-sections,.r-next');if(!('IntersectionObserver'in window)||matchMedia('(prefers-reduced-motion: reduce)').matches){items.forEach(x=>x.classList.add('r-visible'));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('r-visible');observer.unobserve(entry.target)}}),{threshold:.1,rootMargin:'0px 0px -35px 0px'});items.forEach(x=>{x.classList.add('r-reveal');if(x.getBoundingClientRect().top<window.innerHeight){x.classList.add('r-visible')}else{observer.observe(x)}});return()=>observer.disconnect()},[caseId]);
 const visible=useMemo(()=>filter==='All'?projects:projects.filter(p=>p.type===filter),[filter]);
 const openCase=id=>{location.hash='/projects/'+id;window.scrollTo({top:0,behavior:'smooth'})};
 const backToProjects=()=>{location.hash='projects';setCaseId(null)};
 const send=e=>{e.preventDefault();setSent(true)};
 const project=projects.find(p=>p.id===caseId),next=project?projects[(projects.indexOf(project)+1)%projects.length]:null;
 if(project)return <><header className="r-nav r-nav-stuck"><a className="r-brand" href="#home"><span className="r-mark">AM</span><span><b>ARJUN MALHOTRA</b><small>JUNIOR FULL-STACK DEVELOPER</small></span></a><button className="r-text-button" onClick={backToProjects}><ArrowLeft/> All projects</button></header><main className="r-case"><div className="r-case-head"><p className="r-eyebrow">PROJECT {project.n} / 06 <i/> {project.category}</p><h1>{project.name}<span>.</span></h1><p>{project.overview}</p><div className="r-tags">{project.tech.map(x=><span key={x}>{x}</span>)}</div><div className="r-case-art"><Art type={project.art}/></div></div><section className="r-case-sections"><article><b>01 / PROBLEM</b><p>{project.problem}</p></article><article><b>02 / MY APPROACH</b><p>{project.approach}</p></article><article><b>03 / KEY FEATURES</b><ul>{project.features.map(x=><li key={x}><Check/>{x}</li>)}</ul></article><article><b>04 / TECHNOLOGY USED</b><div className="r-tags">{project.tech.map(x=><span key={x}>{x}</span>)}</div></article><article><b>05 / WHAT I LEARNED</b><p>{project.learned}</p></article><article><b>06 / OUTCOME</b><p>{project.outcome}</p></article></section><button className="r-next" onClick={()=>openCase(next.id)}><span>NEXT PROJECT</span><b>{next.name}<ArrowRight/></b></button></main><Footer/><CertModal modal={modal} close={()=>setModal(null)}/></>;
 return <><header className={'r-nav '+(scrolled?'r-nav-stuck':'')}><a className="r-brand" href="#home" onClick={e=>{e.preventDefault();setMenu(false);scrollToSection('home')}}><span className="r-mark">AM</span><span><b>ARJUN MALHOTRA</b><small>JUNIOR FULL-STACK DEVELOPER</small></span></a><nav className={menu?'r-menu-open':''}>{nav.map(([name,id])=><a key={id} href={'#'+id} onClick={e=>{e.preventDefault();setMenu(false);scrollToSection(id)}}>{name}</a>)}<a className="r-mobile-talk" href="#contact" onClick={e=>{e.preventDefault();setMenu(false);scrollToSection('contact')}}>Let's Talk <ArrowUpRight/></a></nav><a className="r-talk" href="#contact" onClick={e=>{e.preventDefault();scrollToSection('contact')}}>Let's Talk <ArrowUpRight/></a><button className="r-menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="home"><section className="r-hero"><div className="r-hero-copy"><div className="r-eyebrow"><i/> JUNIOR FULL-STACK DEVELOPER</div><h1 className="r-person-name">ARJUN<br/>MALHOTRA</h1><p className="r-hero-role">Junior Full-Stack Developer</p><p className="r-hero-tagline">Building thoughtful <em>digital experiences</em> with code.</p><p>I'm Arjun, a junior full-stack developer with a passion for building clean web applications, practical AI solutions and user-friendly digital experiences.</p><div className="r-actions"><a className="r-button r-button-primary" href="#projects">View my projects <ArrowUpRight/></a><a className="r-button r-button-quiet" href="#contact">Let's connect <ArrowRight/></a></div><div className="r-available"><i/> Available for freelance &amp; junior opportunities</div></div><div className="r-hero-art"><div className="r-shape r-shape-one"/><div className="r-shape r-shape-two"/><div className="r-browser"><div className="r-browser-top"><i/><i/><i/><span>arjun.dev / work</span></div><div className="r-browser-body"><div className="r-browser-label">A SMALL THING, WELL MADE</div><h3>Make ideas<br/>work beautifully.</h3><div className="r-browser-line"/><div className="r-browser-footer">React <span/> APIs <span/> Thoughtful UI</div></div></div><div className="r-code-card"><small>app.jsx</small><code><i>function</i> buildIdea() {'{'}<br/>&nbsp; return <b>&lt;GoodWork /&gt;</b><br/>{'}'}</code></div><div className="r-tech-card"><small>IN MY TOOLKIT</small><span>React</span><span>Python</span><span>Node.js</span></div><div className="r-hero-note">LEARNING BY MAKING <i/></div></div><div className="r-hero-bottom"><span>BASED IN BENGALURU, INDIA</span><a href="#about">SCROLL TO EXPLORE <ArrowDown/></a></div></section>
 <section className="r-section r-about" id="about"><div className="r-section-label"><span>01</span> ABOUT ME</div><div className="r-about-grid"><div><h2>A little<br/>about <em>me.</em></h2><p className="r-lead">I'm Arjun, a junior full-stack developer who enjoys turning ideas into functional digital products.</p></div><div className="r-about-copy"><p>Over the past year I've been learning by building: responsive websites, web applications, AI/ML prototypes, dashboards and small automation tools. I enjoy the mix of problem solving and visual detail that makes a product feel intuitive.</p><p>I'm looking for opportunities to contribute, keep growing and make useful things with a thoughtful team.</p><div className="r-info-grid">{[['Based in','Bengaluru, India'],['Experience','1+ Year'],['Focus','Web + AI'],['Availability','Open to opportunities']].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div></div></div><div className="r-stats">{[['1+','Year experience'],['8+','Projects built'],['3','Internships / freelance'],['12+','Technologies']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>
 <section className="r-section r-services" id="services"><div className="r-section-label"><span>02</span> WHAT I DO</div><div className="r-section-heading"><h2>What I can <em>help with.</em></h2><p>Curious, practical development for ideas at every stage.</p></div><div className="r-service-grid">{services.map(([n,title,desc,Icon])=><article key={n}><small>{n}</small><Icon/><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
 <section className="r-section r-skills" id="skills"><div className="r-section-label"><span>03</span> SKILLS & TOOLS</div><div className="r-section-heading"><h2>Learning, building,<br/><em>getting better.</em></h2><p>A growing toolkit built through coursework, small projects and hands-on practice.</p></div><div className="r-skill-grid">{skillGroups.map(([name,level,list])=><article key={name}><div><h3>{name}</h3><small>{level}</small></div><div className="r-skill-pills">{list.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></section>
 <section className="r-section r-projects" id="projects"><div className="r-section-label"><span>04</span> SELECTED PROJECTS</div><div className="r-section-heading"><h2>Learning by <em>making.</em></h2><p>Personal, learning and small collaborative projects, built one thoughtful step at a time.</p></div><div className="r-filters" aria-label="Filter projects">{['All','Web','AI / ML','E-commerce','Automation'].map(x=><button className={filter===x?'active':''} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="r-project-grid">{visible.map(p=><article className="r-project-card" key={p.id}><button className="r-project-visual" onClick={()=>openCase(p.id)} aria-label={'View '+p.name+' project'}><Art type={p.art}/></button><div className="r-project-info"><div className="r-project-meta"><span>PROJECT {p.n}</span><span>{p.category}</span></div><h3>{p.name}<button onClick={()=>openCase(p.id)} aria-label={'Open '+p.name+' case study'}><ArrowUpRight/></button></h3><p>{p.desc}</p><div className="r-tags">{p.tech.map(x=><span key={x}>{x}</span>)}</div><button className="r-view-project" onClick={()=>openCase(p.id)}>View project <ArrowRight/></button></div></article>)}</div></section>
 <section className="r-section r-experience" id="experience"><div className="r-section-label"><span>05</span> EXPERIENCE & EDUCATION</div><div className="r-exp-grid"><div><h2>Early steps,<br/><em>good momentum.</em></h2><p>Learning the craft through practical work, collaboration and steady iteration.</p><div className="r-education"><small>EDUCATION · 2025</small><h3>B.Tech in Computer Science &amp; Engineering</h3><p>National Institute of Digital Technology</p><b>CGPA 8.5 / 10</b><div>Web development · AI · Databases · Cloud · Data structures</div></div></div><div className="r-timeline">{[['2025 — PRESENT','Junior Full-Stack Developer / Freelance Developer','Bengaluru','Developing responsive interfaces and small web applications. Integrating REST APIs, testing features and iterating from feedback.'],['2024 — 2025','Web Development Intern','Kindred Technology Studio · Bengaluru','Worked with a small team on React interfaces, responsive layouts and UI fixes. Used Git and GitHub to review changes and collaborated with designers.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><b>{x[2]}</b><p>{x[3]}</p><small>React · REST APIs · Git / GitHub</small></article>)}</div></div></section>
 <section className="r-section r-certificates" id="certificates"><div className="r-section-label"><span>06</span> LEARNING & RECOGNITION</div><div className="r-section-heading"><h2>Always curious.<br/><em>Always learning.</em></h2><p>Demo portfolio credentials and early milestones from a learning journey.</p></div><div className="r-cert-layout"><div className="r-cert-list"><h3>Certificates</h3>{certificates.map((x,i)=><button key={x[0]} onClick={()=>setModal([...x,i])}><span className="r-cert-icon"><Award/></span><span><b>{x[0]}</b><small>{x[1]} · {x[2]}</small></span><ArrowUpRight/></button>)}<small className="r-demo-note">Illustrative demo credentials. No real certificate IDs are shown.</small></div><div className="r-achievements"><h3>Small milestones</h3>{[['Finalist','College Hackathon'],['Contributor','Open source project'],['Volunteer','Technical events'],['Participant','AI project showcase'],['Member','Department coding club']].map(x=><div key={x[1]}><Sparkles/><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div></section>
 <section className="r-section r-testimonials"><div className="r-section-label"><span>07</span> KIND WORDS</div><div className="r-testimonial-content" key={testimonial}><div className="r-quote-mark">&ldquo;</div><blockquote>{testimonials[testimonial][0]}</blockquote><div className="r-quote-footer"><span className="r-avatar">{testimonials[testimonial][1][0]}</span><span><b>{testimonials[testimonial][1]}</b><small>{testimonials[testimonial][2]}</small></span><div><button onClick={()=>setTestimonial((testimonial+testimonials.length-1)%testimonials.length)} aria-label="Previous testimonial"><ArrowLeft/></button><button onClick={()=>setTestimonial((testimonial+1)%testimonials.length)} aria-label="Next testimonial"><ArrowRight/></button></div><small>0{testimonial+1} / 03</small></div></div></section>
 <section className="r-section r-resume"><div><div className="r-section-label">A CLOSER LOOK</div><h2>My next chapter<br/><em>starts here.</em></h2><p>Take a look at my experience, education, skills and selected projects.</p><a className="r-button r-button-primary" href="/arjun-malhotra-resume.html" target="_blank" rel="noreferrer">View my resume <ArrowUpRight/></a></div><div className="r-resume-card"><small>ARJUN MALHOTRA</small><h3>Junior Full-Stack<br/>Developer</h3><i/><span>1+ YEAR EXPERIENCE</span><div>REACT · JAVASCRIPT · PYTHON · NODE.JS</div></div></section>
 <section className="r-section r-contact" id="contact"><div className="r-section-label"><span>08</span> GET IN TOUCH</div><div className="r-contact-grid"><div><h2>Let's build<br/>something <em>together.</em></h2><p>Have a website idea, project or prototype in mind? I'd love to hear about it.</p><a href="mailto:hello@arjunmalhotra.dev"><Mail/> hello@arjunmalhotra.dev <ArrowUpRight/></a><span><MapPin/> Bengaluru, India</span><small>Fictional demo contact details</small></div><form onSubmit={send}><div className="r-form-row"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label></div><label>Project type<select required value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="">Choose a project type</option>{['Website','Web application','AI / ML prototype','E-commerce','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Message<textarea required rows="4" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Tell me a little about your idea"/></label><button className="r-button r-button-primary" type="submit">{sent?'Message ready — thank you':'Send message'} {sent?<Check/>:<Send/>}</button><small>This demo form validates in your browser and does not send or store your message.</small></form></div></section></main><Footer/><CertModal modal={modal} close={()=>setModal(null)}/></>;
}
function CertModal({modal,close}){const [closing,setClosing]=useState(false);useEffect(()=>{if(!modal)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';const key=e=>{if(e.key==='Escape')dismiss()};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',key)}},[modal]);if(!modal)return null;function dismiss(){if(closing)return;setClosing(true);window.setTimeout(close,280)}return <div className={'r-modal-backdrop '+(closing?'r-modal-closing':'')} onClick={dismiss}><section className="r-modal" role="dialog" aria-modal="true" aria-labelledby="r-cert-title" onClick={e=>e.stopPropagation()}><button onClick={dismiss} aria-label="Close certificate"><X/></button><div className="r-modal-icon"><Award/></div><small>LEARNING MILESTONE · {modal[2]}</small><h2 id="r-cert-title">{modal[0]}</h2><p>Presented by <b>{modal[1]}</b></p><i/><strong>DEMO PORTFOLIO CREDENTIAL</strong><span>Illustrative certificate preview · {modal[2]}</span></section></div>}
createRoot(document.getElementById('root')).render(<App/>);




